site_name: NeuroInsight Hub Enterprise
site_description: Documentation pour la plateforme RH de neurodiversité
site_author: Rémi Chenouri
site_url: https://remichenouri.github.io/neuroscreen-workplace/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: orange
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

nav:
  - Accueil: index.md
  - Guide utilisateur: user_guide.md
  - Référence API: api_reference.md
  - Déploiement: deployment.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
