version: '3.8'

services:
  app:
    build: .
    container_name: ubisoft_analytics_app
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ubisoft_analytics
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
      - mlflow
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    networks:
      - analytics_network

  api:
    build: .
    container_name: ubisoft_analytics_api
    ports:
      - "8000:8000"
    command: uvicorn src.api.endpoints:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ubisoft_analytics
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - db
      - mlflow
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    networks:
      - analytics_network

  db:
    image: postgres:14
    container_name: ubisoft_analytics_db
    environment:
      - POSTGRES_DB=ubisoft_analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - analytics_network

  redis:
    image: redis:7-alpine
    container_name: ubisoft_analytics_redis
    ports:
      - "6379:6379"
    networks:
      - analytics_network

  mlflow:
    image: python:3.9-slim
    container_name: ubisoft_analytics_mlflow
    ports:
      - "5000:5000"
    command: >
      bash -c "pip install mlflow psycopg2-binary &&
               mlflow server --host 0.0.0.0 --port 5000 
               --backend-store-uri postgresql://postgres:password@db:5432/mlflow
               --default-artifact-root ./mlruns"
    depends_on:
      - db
    volumes:
      - mlflow_data:/mlflow
    networks:
      - analytics_network

volumes:
  postgres_data:
  mlflow_data:

networks:
  analytics_network:
    driver: bridge
