apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubisoft-people-analytics
  namespace: default
  labels:
    app: ubisoft-analytics
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ubisoft-analytics
  template:
    metadata:
      labels:
        app: ubisoft-analytics
        version: v1.0.0
    spec:
      containers:
      - name: analytics-app
        image: ghcr.io/remichenouri/ubisoft_people_analytics:latest
        ports:
        - containerPort: 8501
          name: streamlit
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
