site_name: Ubisoft People Analytics
site_description: Documentation plateforme IA RH neurodiversité
site_author: Rémi Chenouri
site_url: https://remichenouri.github.io/ubisoft_people_analytics/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - Accueil: index.md
  - Guide Utilisateur: user_guide.md
  - API Reference: api_reference.md
  - Déploiement: deployment.md

plugins:
  - search:
      lang: fr
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/remichenouri
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/remi-chenouri
