name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/remichenouri/ubisoft_people_analytics:latest .
          docker build -t ghcr.io/remichenouri/ubisoft_people_analytics:${{ github.sha }} .
      
      - name: Push Docker images
        run: |
          docker push ghcr.io/remichenouri/ubisoft_people_analytics:latest
          docker push ghcr.io/remichenouri/ubisoft_people_analytics:${{ github.sha }}
      
      - name: Deploy to Streamlit Cloud
        env:
          STREAMLIT_TOKEN: ${{ secrets.STREAMLIT_TOKEN }}
        run: |
          echo "Deploying to Streamlit Cloud..."
          # Webhook ou API call vers Streamlit Cloud
